Add option to force push to Heroku repository
bitrise-steplib/steps-heroku-deploy pull request #2
Opened 2018-05-23 13:34 UTC by OleMussmann

When `git push`ing a bitrise repository to Heroku, the `--force` option has to be used if a Heroku repository already exists.

This pull request implements this as an option, which defaults to true (force push). Fixes https://github.com/bitrise-steplib/steps-heroku-deploy/issues/1.

2018-05-25 10:48 UTC, trapacska commented
Hey @OleMussmann !

Thank you for the PR. We try to review and reply ASAP!

2018-05-26 11:58 UTC, viktorbenei requested changes
Thanks for the PR @OleMussmann !

One thing for the default value, it definitely should not be the force option. We did not use the force option specifically because with a standard git setup this step works without the `--force` flag. We use it in multiple configs of ours, deploying various bitrise.io services ;)

So even if we do add the `--force` flag (which might be a good feature for some use cases) please do not do that as the default as it might be potentially dangerous.

2018-05-26 11:58 UTC, viktorbenei commented on step.sh
> +if [ "$force_push" == true ] ; then
I think `true` & `false` should be used as strings in the comparison, e.g.

```
if [[ "$force_push" == "true" ]] ; then
```

2018-05-26 11:58 UTC, viktorbenei commented on step.yml
> +  - force_push: "true"
default should be `false` to not to break things

2018-09-21 11:34 UTC, BirmacherAkos approved these changes

2018-09-21 11:36 UTC, merged